-- SQLite

CREATE TABLE CUSTOMERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(128) NOT NULL,
    LASTNAME VARCHAR(155) NOT NULL,
    PHONE VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(32) NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    CITY VARCHAR(64) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    BIRTH_DATE DATETIME NOT NULL
);

CREATE TABLE CAR_MODELS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MODEL_NAME VARCHAR(120) NOT NULL
);

CREATE TABLE POSITIONS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DESCRIPTION VARCHAR(120) NOT NULL
);

CREATE TABLE EMPLOYEES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(16) NOT NULL,
    CONTRACT_DATE DATETIME NOT NULL,
    POSITION_ID INTEGER NOT NULL,

    FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS(ID)
);

CREATE TABLE CAR_BRANDS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BRAND_NAME VARCHAR(32) NOT NULL
);

CREATE TABLE CARS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(120) NOT NULL,
    YEAR INTEGER NOT NULL,
    COLOR VARCHAR(32) NOT NULL,
    KM DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(17) NOT NULL,
    BRAND_ID INTEGER NOT NULL,
    MODEL_ID INTEGER NOT NULL,

    FOREIGN KEY (BRAND_ID) REFERENCES CAR_BRANDS(ID),
    FOREIGN KEY (MODEL_ID) REFERENCES CAR_MODELS(ID)
);

CREATE TABLE LOCATIONS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    TOTAL DECIMAL(10,2) NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    CAR_ID INTEGER NOT NULL,
    EMPLOYEE_ID INTEGER NOT NULL,

    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY (CAR_ID) REFERENCES CARS(ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)
);