-- SQLite

SELECT START_DATE, END_DATE, TOTAL, CUSTOMERS.NAME, CARS.NAME, EMPLOYEES.NAME
FROM LOCATIONS
INNER JOIN CUSTOMERS ON LOCATIONS.CUSTOMER_ID = CUSTOMERS.ID
INNER JOIN EMPLOYEES ON LOCATIONS.EMPLOYEE_ID = EMPLOYEES.ID
INNER JOIN CARS ON LOCATIONS.CAR_ID = CARS.ID